--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/02/2020 14:03:58
-- Server version: 5.5.5-10.1.40-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS ejemplos4yii2poo;

CREATE DATABASE IF NOT EXISTS ejemplos4yii2poo
CHARACTER SET latin1
COLLATE latin1_spanish_ci;

--
-- Set default database
--
USE ejemplos4yii2poo;

--
-- Create table `noticias`
--
CREATE TABLE IF NOT EXISTS noticias (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Titulo varchar(255) DEFAULT NULL,
  Texto varchar(255) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 1638,
CHARACTER SET latin1,
COLLATE latin1_spanish_ci;

-- 
-- Dumping data for table noticias
--
INSERT INTO noticias VALUES
(1, 'Titulo1', 'Prueba1'),
(2, 'Titulo2', 'Prueba2'),
(3, 'Titulo3', 'Prueba3'),
(4, 'Titulo4', 'Prueba4'),
(5, 'Titulo5', 'Prueba5'),
(6, 'Titulo6', 'Prueba6'),
(7, 'Titulo7', 'Prueba7'),
(8, 'Titulo8', 'Prueba8'),
(9, 'Titulo9', 'Prueba9'),
(10, 'Titulo10', 'Prueba10');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;